/* Fairy Star Missions · Round 7. One scene renderer, one input path, local-first data. */
(function(){'use strict';
const E=window.FairyEngine,D=window.FairyData,A=window.FairyArt,DB=window.FairyDB,L=window.FairyLists,h=A.esc;
const app=document.getElementById('app'),modalRoot=document.getElementById('modal-root');
let S,view='home',roomId='bedroom',parentTab='review',reviewDay=E.dayKey(),week=E.weekKey(E.dayKey());
let saving=false,dialogContext=null,returnFocus=null,resizeObserver=null,toastTimer=null,photoURLs=[],preparedBackup=null,parsedBackup=null;
let actorPoint={x:.51,y:.94},drag=null,lastDay=E.dayKey(),fallFrame=0;
const arrivalAnimations=new Set();
const WLD=window.FairyWorld;
let followerFrame=0,leaderHistory=[],lastFollowTick=0,catBusy=false,cuddleCleanup=null,midnightTimer=null;
const followerPoints=new Map(),cuddleBlobs=new Map();let audioContext=null;
const reduced=()=>!!S?.profile.calm||matchMedia('(prefers-reduced-motion: reduce)').matches;
let selections=new Set(),listScope='all';
let touchPress=null,touchClickBlocked=false;
const linePaths={close:'M6 6L18 18M18 6L6 18',back:'M15 5L8 12L15 19',down:'M5 9L12 16L19 9',pin:'M9 3H15L14 9L18 13V15H6V13L10 9Z M12 15V21',camera:'M3 7H8L10 4H14L16 7H21V20H3Z M16 13A4 4 0 1 0 8 13A4 4 0 1 0 16 13',list:'M9 6H21M9 12H21M9 18H21M3 6H4M3 12H4M3 18H4',plus:'M12 4V20M4 12H20',download:'M12 3V15M7 10L12 15L17 10M4 17V21H20V17',reward:'M4 9H20V21H4ZM2 5H22V9H2ZM12 5V21M12 5C5 5 4 1 7 1C10 1 12 5 12 5ZM12 5C19 5 20 1 17 1C14 1 12 5 12 5Z'};
function li(name){return `<svg class="line-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="${linePaths[name]||linePaths.list}"></path></svg>`;}
function button(action,label,cls='secondary',extra=''){return `<button type="button" class="${cls}" data-action="${action}" ${extra}>${label}</button>`;}
function stars(n){return `${n} ${n===1?'star':'stars'}`;}
function done(m,day=E.dayKey()){return E.claimStatus(S,m.id,day)==='approved';}
function available(m,day=E.dayKey()){return !m.oneOffDay||m.oneOffDay===day;}
function recordable(m,day=E.dayKey()){return available(m,day)&&(!done(m,day)||m.repeatable);}
function balance(){return Math.max(0,E.balance(S));}
function goHome(){return button('home',`${li('back')} Go back home`,'go-home');}
function pageTop(title='',copy='',extra=''){return `<div class="page-toolbar">${goHome()}${extra}</div>${title?`<div class="page-heading"><h1>${h(title)}</h1>${copy?`<p>${h(copy)}</p>`:''}</div>`:''}`;}
function progress(value,max,label){const limit=Math.max(1,max),shown=max===0?1:Math.max(0,Math.min(value,limit)),ratio=shown/limit;return `<div class="progress" role="progressbar" aria-label="${h(label)}" aria-valuemin="0" aria-valuemax="${limit}" aria-valuenow="${shown}"><span class="progress-fill" style="width:${ratio*100}%"></span></div>`;}
function pinnedCards(){return S.pins.map(id=>S.rewards.find(r=>r.id===id)).filter(Boolean).map(r=>{const info=L.rewardInfo(S,r);return button('reward',`<div class="pin-title">${A.icon(r.icon,'tiny-icon')}<span>${h(r.name)}</span></div>${progress(info.saved,r.price,r.name)}<small class="pin-progress">${A.icon('star','tiny-icon')}<b>${info.progressText}</b></small>`,`pinned-card glass${info.remaining?'':' ready'}`,`data-id="${h(r.id)}" data-pinned-reward="${h(r.id)}" aria-label="${h(r.name)}: ${info.saved} of ${stars(r.price)} saved"`);}).join('');}
function companionHTML(){return window.FairyCast.followers(S,E.dayKey(),8).map((c,i)=>{const f=WLD.followerSettings(i);return `<span class="companion collected-fairy" data-follow-mission="${h(c.missionId)}" data-claim="${h(c.key)}" data-follow-index="${i}" data-follow-delay="${f.delay}" data-follow-tau="${f.tau}" style="--float-delay:-${i*.51}s;--float-time:${3.6+i%3*.4}s">${A.taskFairy(c.missionId,'companion-art')}</span>`;}).join('');}
function sceneMissions(){return S.missions.filter(m=>m.room===roomId&&available(m));}
function missionStars(){return sceneMissions().map(m=>{const completed=done(m)&&!m.repeatable;return button('mission',`<span class="fairy-shell">${completed?'<span class="completed-fairy-mark">✓</span>':A.taskFairy(m.id)}</span><span class="mission-label">${h(m.name)}</span>${done(m)&&!completed?'<span class="done-dot">✓</span>':''}`,`mission-star mission-fairy${completed?' done':''}`,`data-id="${h(m.id)}" data-mission="${h(m.id)}" data-fairy-index="${window.FairyCast.index(m.id)}" aria-label="${h(m.name)}${completed?' — done today':''}" style="--hover-delay:-${window.FairyCast.index(m.id)*.43}s"`);}).join('');}
function catsHTML(){const found=S.cats[E.dayKey()]||[];return Object.entries(E.catRooms(E.dayKey())).filter(([name,id])=>id===roomId&&!found.includes(name)).map(([name])=>button('cat',A.cat(name),`cat-button`,`data-name="${name}" aria-label="Drag ${name} to Alba for a cuddle" style="left:20%;top:92%"`)).join('');}
function renderHome(){const room=D.rooms.find(r=>r.id===roomId)||D.rooms[0],found=(S.cats[E.dayKey()]||[]).length;return `<main class="scene" id="scene" data-room="${room.id}" aria-label="${h(room.name)}">${A.room(room.id,{seasons:E.activeSeasons(S,E.dayKey())})}${catsHTML()}${missionStars()}<button type="button" id="alba" class="alba-actor" aria-label="Drag Alba onto a mission fairy" aria-describedby="drag-instructions">${A.alba(reduced())}</button><div class="companion-layer" aria-hidden="true">${companionHTML()}</div><div class="scene-top">${button('rooms',`<span>${h(room.name)}</span>${li('down')}`,'room-trigger glass','aria-haspopup="dialog" aria-controls="room-menu"')}<div class="scene-tools">${button('memories',`${li('camera')}<span class="nav-word">Photo album</span>`,'album-button glass','aria-label="Open photo album"')}${button('market',`${A.icon('star','tiny-icon')}<span>${balance()}</span>`,'wallet',`aria-label="${stars(balance())} to spend; open reward list"`)}</div></div><nav class="pinned-strip" aria-label="Pinned rewards">${pinnedCards()}</nav><div class="scene-bottom"><span class="cat-hint glass">Find the cats · ${found} of 2</span><div class="scene-list-actions">${button('list-room',`${li('list')} Mission list`,'list-button glass')}${button('market',`${li('reward')} Reward list`,'list-button glass reward-list-trigger')}</div></div><p id="drag-instructions" class="scene-tip">Tap a fairy, or drag Alba onto it</p></main>`;}
// Position whole hit rectangles, not just symbols. Dense rooms use a collision-free grid.
function layoutScene(){const scene=document.getElementById('scene');if(!scene)return;const W=scene.clientWidth,H=scene.clientHeight;
 scene.classList.remove('garden-dense');const buttons=[...scene.querySelectorAll('.mission-star')],n=buttons.length;scene.classList.toggle('compact-missions',n>6&&(H<730||W<370));if(!n){positionActor();positionCats();return;}
 const strip=scene.querySelector('.pinned-strip'),top=strip&&strip.children.length?strip.offsetTop+strip.offsetHeight+12:76;
 const bw=buttons[0].offsetWidth,bh=buttons[0].offsetHeight;
 const left=bw/2+12,right=W-bw/2-12,minY=top+bh/2,maxY=Math.max(minY,H-Math.min(180,H*.24)-bh/2);
 const maxCols=Math.max(1,Math.floor((W-20)/(bw+8))),cols=Math.min(maxCols,Math.max(1,Math.ceil(Math.sqrt(n*W/Math.max(1,maxY-minY+bh))))),rows=Math.ceil(n/cols);
 const positions=[];
 if(roomId==='garden'){
  const actor=scene.querySelector('#alba'),aw=actor?.offsetWidth||0,ah=actor?.offsetHeight||0;
  const face={left:W*.51-aw*.24,right:W*.51+aw*.24,top:H*.94-ah*.95,bottom:H*.94-ah*.53};
  let scattered=WLD.gardenPositions(buttons.map(b=>b.dataset.id),{W,H,bw,bh,minY,maxY:Math.max(minY,H-112-bh/2),day:E.dayKey(),face});
  if(!scattered){scene.classList.add('garden-dense');const sw=buttons[0].offsetWidth,sh=buttons[0].offsetHeight;scattered=WLD.gardenPositions(buttons.map(b=>b.dataset.id),{W,H,bw:sw,bh:sh,minY:top+sh/2,maxY:H-112-sh/2,day:E.dayKey(),face});}
  if(scattered){buttons.forEach((b,i)=>{b.style.left=scattered[i].x+'px';b.style.top=scattered[i].y+'px';});positionActor();positionCats();return;}
 }
 let hinted=n<=6;
 for(const b of buttons){const a=window.FairyLayout[b.dataset.id];if(!a){hinted=false;break;}const p={x:Math.max(left,Math.min(right,a[0]*W)),y:Math.max(minY,Math.min(maxY,a[1]*H))};if(positions.some(q=>Math.abs(q.x-p.x)<bw+8&&Math.abs(q.y-p.y)<bh+8)){hinted=false;break;}positions.push(p);}
 if(!hinted){positions.length=0;let bottom=Math.max(maxY,minY+(rows-1)*(bh+6));bottom=Math.min(H-75-bh/2,bottom);
  for(let i=0;i<n;i++){const row=Math.floor(i/cols),col=i%cols,count=Math.min(cols,n-row*cols);positions.push({x:count===1?W/2:left+(right-left)*(col/(count-1)),y:rows===1?(minY+bottom)/2:minY+(bottom-minY)*row/(rows-1)});}
 }
 // The enlarged character needs a clear face at the default standing position.
 // This exclusion is fixed, so tapping a star or dragging Alba never moves targets.
 const actor=scene.querySelector('#alba');
 if(actor){const aw=actor.offsetWidth,ah=actor.offsetHeight,face={left:W*.51-aw*.27,right:W*.51+aw*.27,top:H*.94-ah*.96,bottom:H*.94-ah*.51};
  const touchesFace=p=>p.x+bw/2>face.left&&p.x-bw/2<face.right&&p.y+bh/2>face.top&&p.y-bh/2<face.bottom;
  for(let i=0;i<positions.length;i++)if(touchesFace(positions[i])){const origin=positions[i],candidates=[];
   for(let x=left;x<=right+1;x+=Math.max(12,bw/4))for(let y=minY;y<=Math.max(minY,maxY)+1;y+=Math.max(12,bh/4)){const p={x,y};if(touchesFace(p)||positions.some((q,j)=>j!==i&&Math.abs(q.x-x)<bw+8&&Math.abs(q.y-y)<bh+8))continue;candidates.push(p);}
   candidates.sort((a,b)=>Math.hypot(a.x-origin.x,a.y-origin.y)-Math.hypot(b.x-origin.x,b.y-origin.y));if(candidates.length)positions[i]=candidates[0];
  }
 }
 buttons.forEach((b,i)=>{b.style.left=positions[i].x+'px';b.style.top=positions[i].y+'px';});positionActor();positionCats();
}
function positionActor(){const el=document.getElementById('alba'),scene=document.getElementById('scene');if(!el||!scene)return;const W=scene.clientWidth,H=scene.clientHeight,half=el.offsetWidth/2,height=el.offsetHeight;
 const minX=Math.min(W/2,half+4),maxX=Math.max(minX,W-half-4),minY=Math.min(H-8,height+8),maxY=Math.max(minY,H-8);
 const x=Math.max(minX,Math.min(maxX,actorPoint.x*W)),y=Math.max(minY,Math.min(maxY,actorPoint.y*H));el.style.left=x+'px';el.style.top=y+'px';}
function positionCats(){const scene=document.getElementById('scene'),alba=document.getElementById('alba');if(!scene)return;const ar=alba?.getBoundingClientRect(),sr=scene.getBoundingClientRect();const actor=ar?{left:ar.left-sr.left+ar.width*.15,right:ar.right-sr.left-ar.width*.15,top:ar.top-sr.top,bottom:ar.bottom-sr.top}:null;
 for(const el of scene.querySelectorAll('.cat-button')){if(drag?.actor===el)continue;const p=WLD.catPosition(roomId,el.dataset.name,scene.clientWidth,scene.clientHeight,el.offsetWidth,el.offsetHeight,actor);el.style.left=p.x+'px';el.style.top=p.y+'px';}
}
function stopFollowers(){cancelAnimationFrame(followerFrame);followerFrame=0;leaderHistory=[];lastFollowTick=0;}
function startFollowers(){stopFollowers();const scene=document.getElementById('scene'),actor=document.getElementById('alba');if(!scene||!actor||document.hidden)return;
 const els=[...scene.querySelectorAll('.collected-fairy')];if(!els.length)return;
 function tick(now){if(!scene.isConnected||document.hidden){stopFollowers();return;}const sr=scene.getBoundingClientRect(),ar=actor.getBoundingClientRect(),leader={t:now,x:ar.left-sr.left+ar.width/2,y:ar.top-sr.top,w:ar.width,h:ar.height};leaderHistory.push(leader);while(leaderHistory.length>2&&leaderHistory[1].t<now-700)leaderHistory.shift();
 const dt=lastFollowTick?Math.min(70,now-lastFollowTick):16;lastFollowTick=now;
 for(let i=0;i<els.length;i++){const el=els[i],conf=WLD.followerSettings(i),past=leaderHistory.filter(p=>p.t<=now-conf.delay).at(-1)||leaderHistory[0],offset=WLD.halo[i%WLD.halo.length],hw=el.offsetWidth/2,hh=el.offsetHeight/2;
  const target={x:Math.max(hw+3,Math.min(scene.clientWidth-hw-3,past.x+offset[0]*past.w)),y:Math.max(hh+3,Math.min(scene.clientHeight-hh-3,past.y+offset[1]*past.h))};let pt=followerPoints.get(el.dataset.claim);
  if(!pt||reduced()){pt={...target};followerPoints.set(el.dataset.claim,pt);}else{const a=1-Math.exp(-dt/conf.tau);pt.x+=(target.x-pt.x)*a;pt.y+=(target.y-pt.y)*a;}
  el.style.left=pt.x+'px';el.style.top=pt.y+'px';
 }
 if(!reduced())followerFrame=requestAnimationFrame(tick);
 }
 tick(performance.now());
}
function meow(){if(S?.profile.sound===false)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioContext||=new AC();audioContext.resume().catch(()=>{});const t=audioContext.currentTime,o=audioContext.createOscillator(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();o.type='sawtooth';o.frequency.setValueAtTime(590,t);o.frequency.exponentialRampToValueAtTime(850,t+.12);o.frequency.exponentialRampToValueAtTime(380,t+.48);filter.type='lowpass';filter.frequency.setValueAtTime(1450,t);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.025,t+.055);gain.gain.exponentialRampToValueAtTime(.0001,t+.56);o.connect(filter);filter.connect(gain);gain.connect(audioContext.destination);o.start(t);o.stop(t+.58);o.onended=()=>{o.disconnect();filter.disconnect();gain.disconnect();};}catch{/* Sound is optional; no task depends on it. */}}
async function cuddleCat(name){const day=E.dayKey();if(catBusy||(S.cats[day]||[]).includes(name))return;const actor=document.getElementById('alba');if(!actor)return;catBusy=true;meow();settleActor();
 let url=null,timer=null,finish=null;try{
  if(!reduced()&&!cuddleBlobs.has(name)){const response=await fetch(A.cuddleImages[name]);if(!response.ok)throw Error('The cuddle animation could not load.');cuddleBlobs.set(name,await response.blob());}
  if(!actor.isConnected){catBusy=false;return;}
  url=reduced()?A.stillImages[name]:URL.createObjectURL(cuddleBlobs.get(name));
  const image=actor.querySelector('.alba-art');image.src=url;image.alt='Alba cuddling '+name;actor.classList.add('cuddling');actor.dataset.cuddle=name;
  const cat=document.querySelector(`.cat-button[data-name="${name}"]`);if(cat)cat.style.visibility='hidden';
  await new Promise((resolve,reject)=>{if(image.complete&&image.naturalWidth)return resolve();image.onload=resolve;image.onerror=()=>reject(Error('The cuddle animation could not play.'));});
  await commit(s=>E.findCat(s,name,day),{deferRender:true});
  await new Promise(resolve=>{finish=resolve;timer=setTimeout(resolve,1350);cuddleCleanup=()=>{clearTimeout(timer);resolve();};});
  if(actor.isConnected){image.src=reduced()?A.stillImages.alba:A.characterImages.alba;image.alt='Alba';actor.classList.remove('cuddling');delete actor.dataset.cuddle;cat?.remove();const hint=document.querySelector('.cat-hint');if(hint)hint.textContent=`Find the cats · ${(S.cats[E.dayKey()]||[]).length} of 2`;}
 }catch(err){if(actor.isConnected){const image=actor.querySelector('.alba-art');image.src=reduced()?A.stillImages.alba:A.characterImages.alba;image.alt='Alba';actor.classList.remove('cuddling');delete actor.dataset.cuddle;const cat=document.querySelector(`.cat-button[data-name="${name}"]`);if(cat)cat.style.visibility='';}throw err;}
 finally{cuddleCleanup=null;clearTimeout(timer);if(url&&url.startsWith('blob:'))URL.revokeObjectURL(url);catBusy=false;}
}
function openRooms(){const links=[['market','gift','Reward list'],['goals','star','Pinned wishes'],['week','wing','Fairy week'],['memories','album','Photo album'],['parent','check','Bedtime tidy-up'],['help','lantern','How to play']];if(S.features?.moonButtons)links.splice(3,0,['wardrobe','dress','Dress up']);openModal('Choose a room',`<nav id="room-menu" class="room-picker-list" aria-label="Rooms">${D.rooms.map(r=>button('jump',`${A.room(r.id,{thumbnail:true})}<span>${h(r.name)}</span>`,`room-jump${r.id===roomId?' active':''}`,`data-room="${r.id}" ${r.id===roomId?'aria-current="true"':''}`)).join('')}</nav><div class="drawer-links">${links.map(([act,icon,label])=>button(act,`${A.icon(icon)} ${label}`,'drawer-link')).join('')}</div>`,{drawer:true});}
function navigate(next){closeModal(false);view=next;selections.clear();render();window.scrollTo(0,0);}
function render(){if(!S)return;stopFollowers();if(cuddleCleanup)cuddleCleanup();if(fallFrame)actorPoint.y=.94;cancelActorFall();clearArrivals();resizeObserver?.disconnect();document.body.classList.toggle('home-view',view==='home');document.body.classList.toggle('calm',S.profile.calm);const scroll=window.scrollY;
 const pages={home:renderHome,missions:renderList,market:()=>renderRewards(false),goals:()=>renderRewards(true),memories:renderMemories,parent:renderParent,week:renderWeek,wardrobe:renderWardrobe};app.innerHTML=(pages[view]||renderHome)();
 if(view==='home'){layoutScene();startFollowers();resizeObserver=new ResizeObserver(layoutScene);resizeObserver.observe(document.getElementById('scene'));}
 if(view==='memories')hydratePhotos().catch(showError);if(view==='parent'&&parentTab==='data')hydrateBackupInfo().catch(showError);if(view!=='home')window.scrollTo(0,scroll);
}
async function commit(fn,options={}){if(saving)throw Error('Your last change is still saving. Please try again in a moment.');saving=true;
 try{const next=E.clone(S),result=fn(next);E.validateState(next);await DB.save(next,S.revision,options);S=next;if(!options.deferRender)render();return result;}catch(e){if(e.name==='QuotaExceededError')throw Error('This device is out of storage. Your change was not saved.');throw e;}finally{saving=false;}
}
function openModal(title,body,{compact=false,drawer=false,context=null}={}){const previous=modalRoot.querySelector('dialog');if(previous){previous.close();previous.remove();}else returnFocus=document.activeElement;
 dialogContext=context;modalRoot.innerHTML=`<dialog class="modal${compact?' compact':''}${drawer?' left-panel':''}" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${h(title)}</h2><button type="button" class="modal-close" data-action="close" aria-label="Close">${li('close')}</button></div><div class="modal-body">${body}</div><div class="error" role="alert" id="modal-error"></div></dialog>`;
 const dlg=modalRoot.querySelector('dialog');dlg.addEventListener('cancel',e=>{e.preventDefault();closeModal();});dlg.showModal();(dlg.querySelector('[autofocus]')||dlg.querySelector('.modal-close'))?.focus({preventScroll:true});
}
function closeModal(restore=true){const d=modalRoot.querySelector('dialog');if(d){d.close();d.remove();}dialogContext=null;if(restore&&returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else if(restore&&view==='home')document.querySelector('[data-action="rooms"]')?.focus({preventScroll:true});returnFocus=null;}
function showError(err){console.error(err);const el=document.getElementById('modal-error');if(el)el.textContent=err.message||'That change could not be saved.';else toast(err.message||'That change could not be saved.');}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3800);}
function bigStars(n){if(n<1)return '';const count=n>10?1:n;return `<div class="award-stars" role="img" aria-label="Earn ${stars(n)}">${Array.from({length:count},()=>A.icon('star','big-star').replace('viewBox="0 0 100 100"','viewBox="18 18 64 64"')).join('')}${n>10?`<span class="star-count">× ${n}</span>`:''}</div>`;}
function openMission(id){const m=E.mission(S,id);let n=0;const isDone=done(m)&&!m.repeatable;if(!isDone)n=E.previewStars(S,id);const routine=['morning','evening'].includes(m.kind);
 let body=isDone?'<div class="notice good center">Done for today.</div>':n?bigStars(n):'';
 
 body+=button('claim',isDone?'Already done':m.repeatable&&done(m)?'I did it again!':'I did it!','primary wide mission-confirm',`data-id="${h(id)}" ${isDone?'disabled':''}`);
 openModal(m.name,body,{compact:true,context:{type:'mission',id}});
}
async function recordMission(id){const before=balance(),origin=missionOrigin(id);await commit(s=>E.record(s,id));closeModal();selections.delete(id);flyToAlba(id,origin);const gain=balance()-before;celebrate(gain);toast(gain?`Well done! ${stars(gain)} added!`:'Well done! Your mission is recorded.');}
function celebrate(n){window.FairyCelebrations.burst({stars:n,calm:!!S.profile.calm});}

function missionOrigin(id){const el=[...document.querySelectorAll('.mission-star')].find(b=>b.dataset.id===id);if(!el)return null;const r=el.querySelector('.fairy-shell').getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2};}
function clearArrivals(){for(const item of arrivalAnimations){item.animation?.cancel();item.el.remove();item.target?.classList.remove('arriving');}arrivalAnimations.clear();}
function flyToAlba(id,origin,delay=0){if(view!=='home'||!origin||S.profile.calm||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const scene=document.getElementById('scene'),target=[...scene.querySelectorAll('[data-follow-mission]')].filter(el=>el.dataset.followMission===id).at(-1);if(!target)return;
 const sr=scene.getBoundingClientRect(),r=target.getBoundingClientRect(),from={x:origin.x-sr.left,y:origin.y-sr.top},to={x:r.left-sr.left+r.width/2,y:r.top-sr.top+r.height/2};
 target.classList.add('arriving');const el=document.createElement('div');el.className='fairy-arrival';el.setAttribute('aria-hidden','true');el.innerHTML=A.taskFairy(id,'arrival-art');scene.append(el);
 const frames=[];for(let i=0;i<=24;i++){const t=i/24,x=from.x+(to.x-from.x)*t,y=from.y+(to.y-from.y)*t-Math.sin(Math.PI*t)*Math.min(95,scene.clientHeight*.13);frames.push({transform:`translate(${x}px,${y}px) translate(-50%,-50%) rotate(${Math.sin(Math.PI*t)*9}deg) scale(${1-.3*t})`});}
 const item={el,target,animation:null};arrivalAnimations.add(item);item.animation=el.animate(frames,{duration:960,delay,easing:'ease-in-out',fill:'both'});item.animation.finished.catch(()=>{}).then(()=>{target.classList.remove('arriving');el.remove();arrivalAnimations.delete(item);});
}
function cancelActorFall(){cancelAnimationFrame(fallFrame);fallFrame=0;document.getElementById('alba')?.classList.remove('falling');}
function settleActor(){cancelActorFall();const actor=document.getElementById('alba'),scene=document.getElementById('scene');if(!actor||!scene)return;
 const floor=.94,H=scene.clientHeight,from=parseFloat(actor.style.top)/H,delta=floor-from;actorPoint.y=from;
 if(Math.abs(delta)*H<2||S.profile.calm||matchMedia('(prefers-reduced-motion: reduce)').matches){actorPoint.y=floor;positionActor();return;}
 const start=performance.now(),duration=Math.max(260,Math.min(690,Math.sqrt(Math.abs(delta)*H/950)*1000));actor.classList.add('falling');
 function tick(now){if(!actor.isConnected||drag){cancelActorFall();return;}const t=Math.min(1,(now-start)/duration);actorPoint.y=from+delta*t*t;positionActor();if(t<1)fallFrame=requestAnimationFrame(tick);else{fallFrame=0;actor.classList.remove('falling');actorPoint.y=floor;positionActor();}}
 fallFrame=requestAnimationFrame(tick);
}

const groups={morning:'Morning',evening:'Evening',learning:'Learning',behaviour:'Kindness',bonus:'Extra help'};
function listNavigation(active){return `<nav class="list-navigation" aria-label="Mission and reward lists">${button('missions',`${li('list')} Mission list`,`list-tab${active==='missions'?' active':''}`,active==='missions'?'aria-current="page"':'')}${button('market',`${li('reward')} Reward list`,`list-tab${active==='market'?' active':''}`,active==='market'?'aria-current="page"':'')}</nav>`;}
function listRow(m){const complete=done(m)&&!m.repeatable,value=L.missionValue(S,m);return `<div class="mission-row${complete?' recorded':''}" data-mission-row="${h(m.id)}"><label><input type="checkbox" name="mission" value="${h(m.id)}" ${complete?'checked disabled':selections.has(m.id)?'checked':''}><span>${h(m.name)}</span></label><div class="mission-row-end">${complete?'<span class="done-text">Done</span>':''}<span class="mission-value" role="img" aria-label="${h(value.label)}" title="${h(value.label)}"><span class="value-line" aria-hidden="true">${A.icon('star','tiny-icon')}<b>${value.amount}</b></span></span></div></div>`;}
function renderList(){const choices=S.missions.filter(m=>available(m)&&(listScope==='all'||m.room===listScope));return `<main class="page list-page"><div class="page-toolbar">${goHome()}${button('oneoff',`${li('plus')} Add a one-off mission`,'secondary')}</div>${listNavigation('missions')}${listScope!=='all'?`<div class="row between"><span class="muted small">${h(D.rooms.find(r=>r.id===listScope)?.name||'This room')}</span>${button('list-all','Show every room','soft')}</div>`:''}<form data-form="list">${Object.entries(groups).map(([kind,label])=>{const ms=choices.filter(m=>m.kind===kind);return ms.length?`<section class="mission-group"><h2>${label}</h2>${ms.map(listRow).join('')}</section>`:''}).join('')}<div class="batch-footer"><button type="submit" class="primary" id="add-selected" ${selections.size?'':'disabled'}>Add selected</button></div></form></main>`;}
function showOneOff(){openModal('Add a one-off mission',`<form data-form="oneoff" class="stack"><label class="field">Mission name<input type="text" name="name" maxlength="100" placeholder="e.g. Help water the plants" required autofocus></label><label class="field">Stars to earn<input type="number" name="stars" min="1" max="10000" step="1" value="1" required></label><button class="primary wide" type="submit">Add mission</button></form>`,{compact:true});}
function rewardCard(r){const info=L.rewardInfo(S,r),pinned=S.pins.includes(r.id);return `<article class="reward-card">${button('pin',li('pin'),`pin-button${pinned?' pinned':''}`,`data-id="${h(r.id)}" aria-label="${pinned?'Unpin':'Pin'} ${h(r.name)}" aria-pressed="${pinned}"`)}<div class="reward-art">${A.icon(r.icon)}</div><h2>${h(r.name)}</h2><span class="price reward-fraction" aria-label="${info.saved} of ${stars(r.price)} saved">${A.icon('star','tiny-icon')}<b>${info.progressText}</b></span>${progress(info.saved,r.price,r.name)}${info.status?`<small class="muted">${h(info.status)}</small>`:''}<div class="reward-bottom">${button('reward',info.remaining?'Take a look':'Choose reward',info.remaining?'soft wide':'primary wide',`data-id="${h(r.id)}"`)}</div></article>`;}
function rewardListRow(r){const info=L.rewardInfo(S,r),pinned=S.pins.includes(r.id),name=r.id==='cash'?r.name+' · £1':r.name;
 return `<article class="mission-row reward-list-row${info.ready?' ready':''}" data-reward-row="${h(r.id)}" data-star-cost="${r.price}">
 <button type="button" class="reward-row-main" data-action="reward" data-id="${h(r.id)}" aria-label="${h(name)}, ${stars(r.price)}. ${h(info.progressText)}. ${h(info.limit)}">
 <span class="reward-list-art">${A.icon(r.icon)}</span><span class="reward-row-copy"><span class="row-name">${h(name)}</span>${progress(info.saved,r.price,'Progress towards '+name)}${info.status?`<span class="reward-status">${h(info.status)}</span>`:''}</span></button>
 <div class="reward-row-end">${button('pin',li('pin'),`reward-row-pin${pinned?' pinned':''}`,`data-id="${h(r.id)}" aria-label="${pinned?'Unpin':'Pin'} ${h(r.name)}" aria-pressed="${pinned}"`)}${button('reward',`<span class="value-line">${A.icon('star','tiny-icon')}<b>${info.progressText}</b></span><small>${info.remaining?'saved':info.cost===0?'free':'saved'}</small>`,'reward-cost',`data-id="${h(r.id)}" aria-label="${h(name)}: ${info.saved} of ${stars(r.price)} saved; view reward"`)}</div></article>`;
}
function renderRewardList(){const grouped=L.groupRewards(S.rewards);return `<main class="page list-page reward-list-page"><div class="page-toolbar">${goHome()}${button('edit-reward',`${li('plus')} Add a reward`,'secondary','data-id="new"')}</div>${listNavigation('market')}<div class="reward-list-summary"><span class="pill" aria-label="${stars(balance())} available">${A.icon('star','tiny-icon')} ${stars(balance())} available</span>${button('goals','Pinned wishes','soft')}</div>${grouped.map(group=>`<section class="mission-group reward-cost-group" data-reward-tier="${group.id}"><div class="reward-group-heading"><h2>${group.name}</h2><span>${group.range}</span></div>${group.rewards.map(rewardListRow).join('')}</section>`).join('')}${grouped.length?'':'<div class="empty-state"><h2>Add your first family reward.</h2><p>Use “Add a reward” to choose its name and star cost.</p></div>'}</main>`;}
function renderRewards(pinnedOnly){if(!pinnedOnly)return renderRewardList();const rewards=S.pins.map(id=>S.rewards.find(r=>r.id===id)).filter(Boolean);return `<main class="page">${pageTop('Pinned wishes','Each wish uses the same star balance. Spending stars updates all of them.',button('market','Reward list','secondary'))}<div class="reward-grid">${rewards.map(rewardCard).join('')}</div>${!rewards.length?`<div class="empty-state"><h2>Choose a wish to save for.</h2><p>Use the pin button on a reward to add it to the room.</p>${button('market','Open reward list','primary','style="margin-top:18px"')}</div>`:''}</main>`;}
function showReward(id){const r=E.reward(S,id),check=E.canRedeem(S,id),info=L.rewardInfo(S,r);openModal(r.name,`<div class="center">${A.icon(r.icon,'large-icon')}</div><div class="reward-modal-fraction" aria-label="${info.saved} of ${stars(r.price)} saved">${A.icon('star','tiny-icon')}<b>${info.progressText}</b></div>${progress(info.saved,r.price,r.name)}${info.status?`<p class="center muted">${h(info.status)}</p>`:''}${button('redeem-confirm',`Choose for ${stars(check.cost)}`,'primary wide',`data-id="${h(id)}" data-variant="single" ${check.ok?'':'disabled'}`)}${id==='cash'?button('redeem-confirm',`£5 saver · ${stars(S.config.cashSaver)}`,'secondary wide',`data-id="cash" data-variant="saver" ${E.canRedeem(S,'cash',E.dayKey(),'saver').ok?'':'disabled'}`):''}${button('pin',S.pins.includes(id)?'Unpin this wish':'Pin this wish','soft wide',`data-id="${h(id)}"`)}`,{compact:true,context:{type:'reward',id}});}
function confirmSpend(id,variant){const r=E.reward(S,id),check=E.canRedeem(S,id,E.dayKey(),variant);openModal('Use your stars?',`<p class="center">${h(r.name)}${id==='cash'?variant==='saver'?' · £5':' · £1':''}</p><div class="center"><span class="pill">${A.icon('star','tiny-icon')} ${stars(check.cost)}</span></div>${button('spend','Yes, choose this reward','primary wide',`data-id="${h(id)}" data-variant="${variant}" ${check.ok?'':'disabled'}`)}${button('close','Not now','soft wide')}`,{compact:true});}
function renderMemories(){return `<main class="page">${pageTop('Photo album','',button('photo-add',`${li('plus')} Add a photo`,'primary'))}<div class="memory-grid">${S.memories.slice().reverse().map(m=>`<article class="memory"><img data-photo="${h(m.id)}" alt="${h(m.rewardName)}"><h2>${h(m.rewardName)}</h2><small>${h(E.prettyDay(m.day))}</small><br>${button('photo-delete','Remove photo','soft',`data-id="${h(m.id)}"`)}</article>`).join('')}</div>${S.memories.length?'':`<div class="empty-state">${li('camera')}<h2>A little space for happy memories.</h2><p>Tap “Add a photo”, choose a picture, and save it here.</p></div>`}${S.redemptions.filter(r=>!S.memories.some(m=>m.receiptId===r.id)).length?`<h2 class="subheading">Rewards to remember</h2>${S.redemptions.filter(r=>!S.memories.some(m=>m.receiptId===r.id)).slice().reverse().map(r=>`<div class="mission-row"><span class="grow">${h(r.name)}</span>${button('photo-add','Add a photo','secondary',`data-receipt="${h(r.id)}"`)}</div>`).join('')}`:''}</main>`;}
function showPhoto(receiptId=''){const receipt=S.redemptions.find(r=>r.id===receiptId);openModal('Add a photo',`<form data-form="photo" class="stack"><label class="field">Choose a photo<input type="file" name="photo" accept="image/*" required></label><label class="field">Memory title<input type="text" name="title" maxlength="150" value="${h(receipt?.name||'A happy memory')}" required></label><label class="field">Date<input type="date" name="day" value="${receipt?.day||E.dayKey()}" required></label><button class="primary" type="submit">Save to photo album</button><p class="small muted">Saved here only. Keep your original photo and a backup.</p></form>`,{context:{type:'photo',receiptId}});}
async function hydratePhotos(){for(const url of photoURLs)URL.revokeObjectURL(url);photoURLs=[];for(const img of document.querySelectorAll('[data-photo]')){const blob=await DB.get('photos',img.dataset.photo);if(!img.isConnected)continue;if(blob){const url=URL.createObjectURL(blob);photoURLs.push(url);img.src=url;}else img.alt='Photo missing — restore a full backup to recover it.';}}
function renderWeek(){const w=E.weekly(S,week),best=E.bestWeek(S),current=E.weekKey(E.dayKey()),reveal=week<current||[0,5,6].includes(E.parseDay(E.dayKey()).getDay())||S.certificates[week];return `<main class="page">${pageTop('My fairy week')}<div class="row between wrap"><label class="field">Week beginning<input type="date" id="week-select" value="${week}"></label>${button('reveal',reveal?'Reveal my fairy titles':'Ready on Friday','secondary',reveal?'':'disabled')}</div><div class="stats"><div class="stat"><b>${w.total}</b><span>Stars this week</span></div><div class="stat"><b>${best.total}</b><span>My best week</span></div></div>${S.certificates[week]?`<div class="rank-grid">${Object.values(w.scores).map(s=>`<article class="rank-card">${A.icon(s.icon)}<h2>${h(s.title)}</h2><p>${h(s.name)}</p></article>`).join('')}</div>`:`<div class="empty-state">${A.icon('wing','large-icon')}<h2>Four little stories are growing.</h2><p>Come back on Friday to discover your fairy titles.</p></div>`}</main>`;}
function renderWardrobe(){if(!S.features?.moonButtons)return `<main class="page">${pageTop()}<p>Dress up is tucked away for now.</p></main>`;return `<main class="page">${pageTop('Dress up')}<div class="reward-grid">${D.outfits.map(o=>`<article class="card center">${A.avatar(o.color,true,o.accent)}<h2>${h(o.name)}</h2>${button('outfit','Choose','secondary',`data-id="${o.id}"`)}</article>`).join('')}</div></main>`;}
function renderParent(){const tabs=[['review','Bedtime tidy-up'],['missions','Edit missions'],['rewards','Edit rewards'],['settings','Settings'],['data','Backups'],['history','Star history']];const pages={review:renderReview,missions:renderMissionSettings,rewards:renderRewardSettings,settings:renderSettings,data:renderData,history:renderHistory};return `<main class="page">${pageTop('For grown-ups')}<nav class="tabs">${tabs.map(([key,label])=>button('parent-tab',label,`tab${parentTab===key?' active':''}`,`data-tab="${key}"`)).join('')}</nav>${(pages[parentTab]||renderReview)()}</main>`;}
function renderReview(){const claims=S.claims.filter(c=>c.day===reviewDay&&c.status==='approved'),custom=S.ledger.filter(a=>a.day===reviewDay&&a.kind==='custom');return `<div class="row between wrap"><label class="field">Review day<input type="date" id="review-day" value="${reviewDay}" max="${E.dayKey()}"></label>${button('custom-award','Add a completed one-off','secondary')}</div><div class="notice" style="margin:18px 0">Remove a task that should not count, for example when you had to ask twice. Related routine stars update automatically.</div>${claims.map(c=>`<div class="mission-row"><div class="grow"><div class="row-name">${h(c.name)}</div></div>${button('remove-claim','Remove','soft',`data-id="${h(c.id)}"`)}</div>`).join('')}${custom.map(a=>`<div class="mission-row"><span class="grow">${h(a.name)}</span>${button('remove-custom','Remove','soft',`data-id="${h(a.id)}"`)}</div>`).join('')}${claims.length+custom.length?'':'<div class="empty-state"><h2>No tasks recorded for this day.</h2></div>'}`;}
function renderMissionSettings(){return Object.entries(groups).map(([kind,label])=>`<section class="mission-group"><h2>${label}</h2>${S.missions.filter(m=>m.kind===kind&&!m.oneOffDay).map(m=>`<div class="mission-row"><span class="grow">${h(m.name)}</span>${button('edit-mission','Edit','soft',`data-id="${h(m.id)}"`)}</div>`).join('')}</section>`).join('');}
function renderRewardSettings(){return `<div style="margin-bottom:18px">${button('edit-reward','Add reward','primary','data-id="new"')}</div>${S.rewards.map(r=>`<div class="mission-row"><div class="grow">${h(r.name)}<p class="small muted">${stars(r.price)}</p></div>${button('edit-reward','Edit','soft',`data-id="${h(r.id)}"`)}</div>`).join('')}`;}
const configLabels={morningStars:'Morning routine stars',morningThreshold:'Morning jobs needed',eveningStars:'Evening routine stars',eveningThreshold:'Evening jobs needed',learningCap:'Daily learning star limit',behaviourBonus:'All kindnesses bonus',weeklyBonus:'Full-week star bonus',cashCap:'Weekly pocket money limit (stars)',cashSaver:'£5 saver cost (stars)'};
function renderSettings(){return `<form data-form="settings" class="stack"><section class="card stack"><label class="field">Child’s name<input name="name" value="${h(S.profile.name)}" maxlength="40" required></label><label class="checkbox"><input name="calm" type="checkbox" ${S.profile.calm?'checked':''}> Calmer fairy movement</label></section><section class="card stack"><h2>Star values</h2><div class="form-grid">${Object.entries(configLabels).map(([key,label])=>`<label class="field">${label}<input name="${key}" type="number" min="${key.endsWith('Threshold')?1:0}" max="${key==='morningThreshold'?S.missions.filter(m=>m.kind==='morning').length:key==='eveningThreshold'?S.missions.filter(m=>m.kind==='evening').length:10000}" step="1" value="${S.config[key]}" required></label>`).join('')}</div><p class="small muted">Changes apply to future awards. Existing earned stars are not rescaled.</p></section><button type="submit" class="primary">Save settings</button></form>`;}
function showMissionEditor(id){const m=E.mission(S,id),routine=['morning','evening'].includes(m.kind);openModal('Edit mission',`<form data-form="edit-mission" class="stack"><label class="field">Name<input name="name" value="${h(m.name)}" maxlength="100" required></label>${routine?'<p class="small muted">Routine star values are in Settings.</p>':`<label class="field">Stars<input name="stars" type="number" value="${m.stars}" min="0" max="10000" step="1" required></label>`}<label class="field">Room<select name="room">${D.rooms.map(r=>`<option value="${r.id}" ${r.id===m.room?'selected':''}>${h(r.name)}</option>`).join('')}</select></label>${m.kind==='bonus'&&!m.unprompted?`<label class="checkbox"><input type="checkbox" name="repeatable" ${m.repeatable?'checked':''}> Can be recorded on separate occasions</label>`:''}<button type="submit" class="primary">Save mission</button></form>`,{context:{type:'edit-mission',id}});}
function showRewardEditor(id){const isNew=id==='new',r=isNew?{name:'',price:10,note:'',icon:'gift',available:true,cooldown:{type:'none',days:0}}:E.reward(S,id),pictures={gift:'Present',books:'Books',moon:'Bedtime',chocolate:'Chocolate',bath:'Bath',plate:'Meal',dress:'Clothes',tv:'Movie',icecream:'Ice cream',teddy:'Play',sun:'Day out',swim:'Swimming',house:'Sleepover',crown:'Crown',coins:'Pocket money',flower:'Flower',tree:'Garden',star:'Star'};
 openModal(isNew?'Add a reward':'Edit reward',`<form data-form="edit-reward" class="stack"><label class="field">Reward name<input name="name" value="${h(r.name)}" placeholder="e.g. Choose our family game" maxlength="100" required autofocus></label><div class="form-grid"><label class="field">Star cost<input name="price" type="number" value="${r.price}" min="0" max="10000" step="1" required></label><label class="field">Picture<select name="icon">${L.rewardIcons.map(icon=>`<option value="${icon}" ${r.icon===icon?'selected':''}>${pictures[icon]||icon}</option>`).join('')}</select></label></div><label class="field">Note (optional)<input name="note" value="${h(r.note||'')}" maxlength="150" placeholder="Anything to remember"></label><label class="field">Use limit<select name="cooldown" id="reward-use-limit">${[['none','No repeat limit'],['week','Once each week'],['month','Once each calendar month'],['days','Days between uses']].map(([key,label])=>`<option value="${key}" ${r.cooldown.type===key?'selected':''}>${label}</option>`).join('')}</select></label><label class="field" id="reward-days-field" ${r.cooldown.type==='days'?'':'hidden'}>Days between uses<input type="number" name="days" min="1" max="3650" step="1" value="${Math.max(1,r.cooldown.days||1)}" ${r.cooldown.type==='days'?'required':'disabled'}></label><label class="checkbox"><input name="available" type="checkbox" ${r.available?'checked':''}> Available to choose</label><button type="submit" class="primary wide">${isNew?'Add reward':'Save reward'}</button></form>`,{context:{type:'edit-reward',id}});
}
function renderData(){return `<div class="stack"><section class="card stack"><h2>Ready for the iPad</h2><p class="small muted" id="install-status" role="status">${window.FSM_PREVIEW?'Mac practice copy. Install the website version on the iPad.':'Checking offline installation…'}</p><p class="small muted">A new device starts at zero. Records and photos stay on the device that created them; there is no automatic sync.</p></section><section class="card stack"><h2>A safe copy</h2><p class="small muted">Save a full backup outside this app. It includes your records and photo album photos. Local data and snapshots can be lost if the browser’s storage is cleared.</p><div class="row wrap">${button('backup',`${li('download')} Export backup`,'primary')}${button('restore','Restore a backup','secondary')}</div></section><section class="card stack"><h2>Finish testing</h2><p class="small muted">Start at zero while keeping your missions, reward choices, prices, pins, settings and photo album. Test completions, stars, reward-use history, weekly progress and found cats are cleared. Nothing resets automatically.</p>${button('clear-test-progress','Clear test progress','soft')}</section><section class="card stack"><h2>On-device snapshots</h2><div id="snapshot-list" class="small muted">Loading…</div></section><section class="card stack"><h2>Photo album</h2><p id="photo-size" class="storage-size">Loading…</p>${button('memories','Open photo album','soft')}</section></div>`;}
function showCleanStart(){openModal('Start with zero stars?',`<form data-form="clean-start" class="stack"><p>Clears test stars earned and spent, completed missions, reward-use history, weekly progress and found cats.</p><p><strong>Keep:</strong> all mission and reward definitions, prices, pins, settings and photo album photos.</p><p class="small muted">A snapshot of your current records is saved before the reset. Export a full backup first for an extra copy outside this browser.</p>${button('backup','Export a backup first','secondary')}<label class="field">Type START to confirm<input name="confirmation" autocomplete="off" autocapitalize="characters" spellcheck="false" pattern="START" required placeholder="START"></label><button type="submit" class="primary wide">Clear test progress and start at zero</button>${button('close','Cancel','soft wide')}</form>`,{compact:true,context:{type:'clean-start'}});}
let offlineInstallState='Checking offline installation…';
function updateInstallStatus(){const el=document.getElementById('install-status');if(el&&!window.FSM_PREVIEW)el.textContent=offlineInstallState;}
async function prepareOffline(){
 if(window.FSM_PREVIEW)return;
 if(!('serviceWorker' in navigator)||!isSecureContext){offlineInstallState='Open the hosted HTTPS website in Safari to install offline support.';updateInstallStatus();return;}
 try{
  const reg=await navigator.serviceWorker.register('./sw.js');
  const showWorker=worker=>{
   if(!worker)return;
   const check=()=>{if(worker.state==='activated'){offlineInstallState='Offline ready — the app and all artwork have been saved on this device.';updateInstallStatus();}else if(worker.state==='redundant'){offlineInstallState='Offline installation did not finish. Stay online, sign in to the private website and reopen the app.';updateInstallStatus();}};
   worker.addEventListener('statechange',check);check();
  };
  reg.addEventListener('updatefound',()=>showWorker(reg.installing));
  showWorker(reg.installing||reg.waiting||reg.active);
  navigator.serviceWorker.ready.then(()=>{offlineInstallState='Offline ready — the app and all artwork have been saved on this device.';updateInstallStatus();});
 }catch(err){offlineInstallState='Offline installation did not finish. Stay online and reopen the app.';updateInstallStatus();console.warn('Offline setup',err);}
}
async function hydrateBackupInfo(){updateInstallStatus();const snaps=await DB.snapshotList(),list=document.getElementById('snapshot-list');if(list)list.innerHTML=snaps.length?snaps.map(s=>`<div class="history-row"><span>${h(new Date(s.value.at).toLocaleString('en-GB'))}</span>${button('snapshot','Restore','soft',`data-key="${h(s.key)}"`)}</div>`).join(''):'Daily snapshots appear after you start using the app.';const bytes=await DB.photoBytes(),size=document.getElementById('photo-size');if(size)size.textContent=`${S.memories.length} photos · ${(bytes/1024/1024).toFixed(1)} MB`;}
function renderHistory(){return `<h2 class="subheading">Stars earned</h2>${S.ledger.slice().reverse().map(a=>`<div class="history-row"><div>${h(a.name)}<br><small>${h(E.prettyDay(a.day))}</small></div><b>+${a.stars}</b></div>`).join('')}<h2 class="subheading">Rewards chosen</h2>${S.redemptions.slice().reverse().map(r=>`<div class="history-row"><div>${h(r.name)}<br><small>${h(E.prettyDay(r.day))} · ${stars(r.cost)}</small></div>${button('undo-spend','Undo spend','soft',`data-id="${h(r.id)}"`)}</div>`).join('')}`;}
function showCustomAward(){openModal('Add a completed one-off',`<form data-form="custom-award" class="stack"><label class="field">What did she do?<input name="name" maxlength="100" required autofocus></label><label class="field">Stars<input name="stars" type="number" min="1" max="10000" step="1" value="1" required></label><button type="submit" class="primary">Add completed mission</button></form>`,{compact:true});}
function showHelp(){openModal('How to play',`<p>Tap a fairy to open its mission. Alba stays still when you tap. You can also drag Alba onto a fairy. Let her go and she lands gently on the floor.</p><p>Open Mission list to tick off several things together. Nothing is selected for you.</p><p>Tap the room name to choose another room. Tap outside the menu to close it.</p><p>Open Reward list to browse by star cost, see your progress, and add a family reward. Pin rewards to show their progress above the room. Use the camera button for your photo album.</p>`,{compact:true});}
function confirmAction(title,copy,action,extra=''){openModal(title,`<p>${h(copy)}</p>${button(action,'Confirm','primary wide',extra)}${button('close','Cancel','soft wide')}`,{compact:true});}
async function dispatch(action,b){if(rollover()){toast('A new day! Your missions are ready again.');return;}switch(action){
 case 'home':navigate('home');break;
 case 'rooms':openRooms();break;
 case 'jump':roomId=b.dataset.room;actorPoint={x:.51,y:.94};navigate('home');break;
 case 'list-room':listScope='all';navigate('missions');break;
 case 'list-all':listScope='all';selections.clear();render();break;
 case 'missions':listScope='all';navigate('missions');break;
 case 'market':case 'goals':case 'memories':case 'parent':case 'week':case 'wardrobe':navigate(action);break;
 case 'close':closeModal();break;
 case 'mission':openMission(b.dataset.id);break;
 case 'claim':await recordMission(b.dataset.id);break;
 case 'oneoff':showOneOff();break;
 case 'cat':meow();toast(`Drag ${b.dataset.name} to Alba for a cuddle.`);break;
 case 'pin':{const ctx=dialogContext,id=b.dataset.id;await commit(s=>{if(s.pins.includes(id))s.pins=s.pins.filter(x=>x!==id);else s.pins.push(id);});if(ctx?.type==='reward')showReward(ctx.id);break;}
 case 'reward':showReward(b.dataset.id);break;
 case 'redeem-confirm':confirmSpend(b.dataset.id,b.dataset.variant);break;
 case 'spend':{const receipt=await commit(s=>E.redeem(s,b.dataset.id,E.dayKey(),b.dataset.variant));openModal('A happy memory to make',`<p class="center">${h(receipt.name)} is yours to enjoy.</p>${button('photo-add',`${li('camera')} Add a photo`,'primary wide',`data-receipt="${h(receipt.id)}"`)}${button('close','Later','soft wide')}`,{compact:true});break;}
 case 'photo-add':showPhoto(b.dataset.receipt||'');break;
 case 'photo-delete':confirmAction('Remove this photo?','This removes only the photo album copy on this device.','delete-photo',`data-id="${h(b.dataset.id)}"`);break;
 case 'delete-photo':{const id=b.dataset.id;await commit(s=>s.memories=s.memories.filter(m=>m.id!==id),{deletePhoto:id});closeModal();break;}
 case 'reveal':await commit(s=>s.certificates[week]={revealedAt:new Date().toISOString()});break;
 case 'outfit':if(S.features?.moonButtons)await commit(s=>E.buyOutfit(s,b.dataset.id));break;
 case 'parent-tab':parentTab=b.dataset.tab;render();break;
 case 'remove-claim':{const c=S.claims.find(c=>c.id===b.dataset.id);openModal('Remove this task?',`<p>${h(c.name)}</p><form data-form="remove-claim" class="stack"><label class="field">Reason<select name="reason"><option>Asked twice</option><option>Not done yet</option><option>Added by mistake</option></select></label><button type="submit" class="primary">Remove task</button></form>`,{compact:true,context:{type:'remove-claim',id:c.id}});break;}
 case 'remove-custom':confirmAction('Remove this one-off award?','Its stars will be removed from this day.','delete-custom',`data-id="${h(b.dataset.id)}"`);break;
 case 'delete-custom':await commit(s=>s.ledger=s.ledger.filter(a=>a.id!==b.dataset.id));closeModal();break;
 case 'custom-award':showCustomAward();break;
 case 'edit-mission':showMissionEditor(b.dataset.id);break;
 case 'edit-reward':showRewardEditor(b.dataset.id);break;
 case 'clear-test-progress':showCleanStart();break;
 case 'backup':{preparedBackup=await DB.exportFile(S);const url=URL.createObjectURL(preparedBackup);photoURLs.push(url);openModal('Save your backup',`<p>Save this file somewhere safe outside the app.</p><a class="primary wide" href="${url}" download="${h(preparedBackup.name)}">Save backup file</a>${typeof navigator.share==='function'?button('share-backup','Share / Save to Files','secondary wide'):''}${button('backup-saved','I have saved a copy','soft wide')}`,{compact:true});break;}
 case 'share-backup':if(preparedBackup)await navigator.share({files:[preparedBackup],title:'Fairy Star Missions backup'});break;
 case 'backup-saved':await commit(s=>s.lastExternalBackup=new Date().toISOString());closeModal();toast('Backup date updated.');break;
 case 'restore':openModal('Restore a backup','<p>Choose a full Fairy Star Missions backup. Nothing changes until you confirm.</p><input type="file" id="restore-file" accept="application/json,.json">',{compact:true});break;
 case 'confirm-restore':{if(!parsedBackup)throw Error('Choose a backup first.');const next=E.clone(parsedBackup.state);E.migrate(next);E.validateState(next);await DB.save(next,S.revision,{replacePhotos:parsedBackup.photos,restore:true});S=next;parsedBackup=null;closeModal();view='home';render();toast('Backup restored.');break;}
 case 'snapshot':{const snap=await DB.get('snapshots',b.dataset.key);if(!snap)throw Error('Snapshot not found.');parsedBackup={state:snap.state,snapshot:true};confirmAction('Restore these records?','This replaces current stars and settings. Existing photo album photos are kept.','confirm-snapshot');break;}
 case 'confirm-snapshot':{if(!parsedBackup?.snapshot)throw Error('Choose a snapshot first.');const next=E.clone(parsedBackup.state);for(const m of [...next.memories])if(!await DB.get('photos',m.id))next.memories=next.memories.filter(x=>x.id!==m.id);E.migrate(next);E.validateState(next);await DB.save(next,S.revision,{restore:true});S=next;parsedBackup=null;closeModal();view='home';render();break;}
 case 'undo-spend':confirmAction('Undo this reward spend?','The stars will return to the balance. The correction will stay in the saved records.','confirm-undo-spend',`data-id="${h(b.dataset.id)}"`);break;
 case 'confirm-undo-spend':await commit(s=>{const r=s.redemptions.find(r=>r.id===b.dataset.id);if(!r)throw Error('Reward not found.');s.cancelledRedemptions||=[];s.cancelledRedemptions.push({...r,cancelledAt:new Date().toISOString()});s.redemptions=s.redemptions.filter(x=>x.id!==r.id);if(r.rewardId==='skip'&&!s.redemptions.some(x=>x.rewardId==='skip'&&x.day===r.day)){s.skips=s.skips.filter(x=>x!==r.day);for(const kind of ['morning','evening'])if(E.blockProgress(s,r.day,kind).approved<s.config[kind+'Threshold'])s.ledger=s.ledger.filter(x=>x.key!==`${kind}:${r.day}`);const w=E.weekKey(r.day);if(!Array.from({length:7},(_,i)=>E.addDays(w,i)).every(d=>E.hasAward(s,`morning:${d}`)&&E.hasAward(s,`evening:${d}`)))s.ledger=s.ledger.filter(x=>x.key!==`week:${w}`);}});closeModal();break;
 case 'help':showHelp();break;
 }}
async function submit(form){if(form.dataset.form!=='photo'&&rollover()){toast('A new day! Choose today’s missions.');return;}if(!form.reportValidity())return;const f=new FormData(form);switch(form.dataset.form){
 case 'clean-start':{
  if(dialogContext?.type!=='clean-start'||String(f.get('confirmation'))!=='START')throw Error('Type START to confirm.');
  await commit(s=>E.clearTestProgress(s),{reset:true,deferRender:true});
  selections.clear();preparedBackup=null;parsedBackup=null;reviewDay=E.dayKey();week=E.weekKey(reviewDay);lastDay=reviewDay;actorPoint={x:.51,y:.94};
  closeModal();navigate('home');toast('Ready for a fresh start: zero stars. Your missions, rewards and photos are kept.');break;
 }

 case 'list':{const ids=[...new Set(f.getAll('mission'))];if(!ids.length)throw Error('Choose a mission first.');const before=balance();await commit(s=>{for(const id of ids)E.record(s,id);});selections.clear();render();const gain=balance()-before;celebrate(gain);toast(gain?`Well done! ${stars(gain)} added!`:'Well done! Your selected missions are recorded.');break;}
 case 'oneoff':{const m=await commit(s=>E.addOneOff(s,{name:String(f.get('name')),stars:Number(f.get('stars'))}));closeModal();view='missions';listScope='all';selections.clear();render();requestAnimationFrame(()=>document.querySelector(`input[value="${m.id}"]`)?.closest('.mission-row')?.scrollIntoView({block:'center',behavior:'auto'}));toast('One-off mission added, ready to tick when done.');break;}
 case 'photo':{const file=f.get('photo');if(!file||!file.size)throw Error('Choose a photo first.');const name=E.text(String(f.get('title')),150),day=String(f.get('day'));E.parseDay(day);const receiptId=dialogContext?.receiptId||null;const submitButton=form.querySelector('[type="submit"]');submitButton.disabled=true;try{const blob=await DB.compressPhoto(file),id=E.uid();await commit(s=>s.memories.push({id,receiptId,rewardName:name,day,createdAt:new Date().toISOString()}),{photo:{id,blob},deferRender:true});closeModal();navigate('memories');toast('Photo saved to your photo album.');}finally{if(submitButton.isConnected)submitButton.disabled=false;}break;}
 case 'remove-claim':{const id=dialogContext.id;await commit(s=>E.retractClaim(s,id,String(f.get('reason'))));closeModal();toast('Task removed and stars updated.');break;}
 case 'custom-award':await commit(s=>E.customAward(s,{name:String(f.get('name')),stars:Number(f.get('stars')),virtues:['helper'],save:false},reviewDay));closeModal();toast('Completed one-off added.');break;
 case 'edit-mission':{const id=dialogContext.id;await commit(s=>{const m=E.mission(s,id);m.name=E.text(String(f.get('name')));m.room=String(f.get('room'));if(!['morning','evening'].includes(m.kind))m.stars=E.integer(Number(f.get('stars')));if(m.kind==='bonus'&&!m.unprompted)m.repeatable=f.has('repeatable');});closeModal();break;}
 case 'edit-reward':{const id=dialogContext.id,r=await commit(s=>L.saveReward(s,{name:String(f.get('name')),price:Number(f.get('price')),icon:String(f.get('icon')),note:String(f.get('note')||''),available:f.has('available'),cooldown:{type:String(f.get('cooldown')),days:Number(f.get('days'))}},id));closeModal();if(view==='market')requestAnimationFrame(()=>document.querySelector(`[data-reward-row="${r.id}"]`)?.scrollIntoView({block:'center',behavior:'auto'}));toast(id==='new'?'Reward added to your reward list.':'Reward saved.');break;}
 case 'settings':await commit(s=>{s.profile.name=E.text(String(f.get('name')),40);s.profile.calm=f.has('calm');s.profile.readAloud=false;for(const key of Object.keys(configLabels))s.config[key]=Number(f.get(key));});toast('Settings saved.');break;
 }}
function handleClick(e){if(touchClickBlocked){e.preventDefault();return;}const b=e.target.closest('[data-action]');if(b){dispatch(b.dataset.action,b).catch(showError);return;}const d=e.target;if(d.tagName==='DIALOG'){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}}
app.addEventListener('click',handleClick);modalRoot.addEventListener('click',handleClick);
// Activate touch buttons on pointer-up rather than relying on delayed compatibility
// clicks after a drag. A new press (or key) clears the single-gesture click guard.
document.addEventListener('pointerdown',e=>{
 touchClickBlocked=false;touchPress=null;
 if(e.pointerType!=='touch'||!e.isPrimary)return;
 const b=e.target.closest('button');
 if(b&&b.id!=='alba'&&!b.classList.contains('cat-button')&&!b.disabled&&(app.contains(b)||modalRoot.contains(b)))touchPress={id:e.pointerId,x:e.clientX,y:e.clientY,b};
},true);
document.addEventListener('pointerup',e=>{
 const t=touchPress;if(!t){if(e.pointerType==='touch'&&e.target.tagName==='DIALOG'){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){touchClickBlocked=true;e.preventDefault();closeModal();}}return;}if(e.pointerId!==t.id)return;touchPress=null;
 if(!t.b.isConnected||Math.hypot(e.clientX-t.x,e.clientY-t.y)>10)return;
 touchClickBlocked=true;e.preventDefault();
 if(t.b.dataset.action)dispatch(t.b.dataset.action,t.b).catch(showError);
 else if(t.b.type==='submit'&&t.b.form)t.b.form.requestSubmit(t.b);
});
document.addEventListener('pointercancel',()=>{touchPress=null;});
document.addEventListener('keydown',()=>{touchClickBlocked=false;},true);

for(const root of [app,modalRoot])root.addEventListener('submit',e=>{if(e.target.matches('[data-form]')){e.preventDefault();submit(e.target).catch(showError);}});
app.addEventListener('change',e=>{const el=e.target;if(el.matches('input[name="mission"]')){if(el.checked)selections.add(el.value);else selections.delete(el.value);const b=document.getElementById('add-selected');if(b)b.disabled=!selections.size;}
 if(el.id==='review-day'){try{E.parseDay(el.value);if(el.value>E.dayKey())throw Error('Choose today or an earlier day.');reviewDay=el.value;render();}catch(err){showError(err);}}
 if(el.id==='week-select'){try{week=E.weekKey(el.value);render();}catch(err){showError(err);}}
});
modalRoot.addEventListener('change',e=>{if(e.target.id==='reward-use-limit'){const field=document.getElementById('reward-days-field'),input=field.querySelector('input'),show=e.target.value==='days';field.hidden=!show;input.disabled=!show;input.required=show;}
 if(e.target.id==='restore-file'&&e.target.files?.[0])DB.parseBackup(e.target.files[0]).then(result=>{parsedBackup=result;confirmAction('Replace this saved world?','Your current records and photo album photos will be replaced by the selected backup. Export your current data first.','confirm-restore');}).catch(showError);});
// Single drag path for Alba and the cats. A moved cat does not generate a tap.
app.addEventListener('pointerdown',e=>{const actor=e.target.closest('#alba,.cat-button');if(!actor||view!=='home'||catBusy||(e.pointerType==='mouse'&&e.button!==0)||!e.isPrimary)return;
 if(rollover())return;const kind=actor.id==='alba'?'alba':'cat';if(kind==='alba')cancelActorFall();
 const r=actor.getBoundingClientRect(),scene=document.getElementById('scene').getBoundingClientRect();
 drag={kind,name:actor.dataset.name,id:e.pointerId,startX:e.clientX,startY:e.clientY,offsetX:e.clientX-(r.left+r.width/2),offsetY:e.clientY-r.bottom,scene,moved:false,actor,originalLeft:actor.style.left,originalTop:actor.style.top};actor.setPointerCapture(e.pointerId);
});
function dragTarget(x,y){return [...document.querySelectorAll('.mission-star')].find(el=>{const r=el.getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom;});}
function overAlba(x,y){const el=document.getElementById('alba');if(!el)return false;const r=el.getBoundingClientRect();return x>=r.left+r.width*.13&&x<=r.right-r.width*.13&&y>=r.top+r.height*.08&&y<=r.bottom;}
app.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(!drag.moved&&Math.hypot(dx,dy)<5)return;drag.moved=true;drag.actor.classList.add('dragging');const r=drag.scene;
 if(drag.kind==='alba'){actorPoint.x=Math.max(.06,Math.min(.94,(e.clientX-drag.offsetX-r.left)/r.width));actorPoint.y=Math.max(.24,Math.min(.94,(e.clientY-drag.offsetY-r.top)/r.height));positionActor();const target=dragTarget(e.clientX,e.clientY);document.querySelectorAll('.mission-star').forEach(el=>el.classList.toggle('drag-target',el===target));}
 else {drag.actor.style.left=(e.clientX-drag.offsetX-r.left)+'px';drag.actor.style.top=(e.clientY-drag.offsetY-r.top)+'px';document.getElementById('alba')?.classList.toggle('cuddle-target',overAlba(e.clientX,e.clientY));}e.preventDefault();
});
function endDrag(e,cancelled=false){if(!drag||drag.id!==e.pointerId)return;const info=drag;drag=null;info.actor.classList.remove('dragging');try{info.actor.releasePointerCapture(e.pointerId);}catch{}document.querySelectorAll('.drag-target,.cuddle-target').forEach(el=>el.classList.remove('drag-target','cuddle-target'));
 if(info.moved){touchClickBlocked=true;const timer=setTimeout(()=>touchClickBlocked=false,380);
  if(info.kind==='alba'){const target=cancelled?null:dragTarget(e.clientX,e.clientY);settleActor();if(target)openMission(target.dataset.id);}
  else if(!cancelled&&overAlba(e.clientX,e.clientY)){cuddleCat(info.name).catch(showError);}
  else {info.actor.style.left=info.originalLeft;info.actor.style.top=info.originalTop;}
 }
}
app.addEventListener('pointerup',e=>endDrag(e));app.addEventListener('pointercancel',e=>endDrag(e,true));
app.addEventListener('keydown',e=>{if(e.target.id==='alba'&&(e.key==='Enter'||e.key===' ')){e.preventDefault();document.querySelector('.mission-star')?.focus();}if(e.target.classList.contains('cat-button')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();cuddleCat(e.target.dataset.name).catch(showError);}});
function scheduleMidnight(){clearTimeout(midnightTimer);midnightTimer=setTimeout(()=>{rollover();scheduleMidnight();},WLD.nextMidnightDelay()+20);}
function rollover(){if(!S)return false;const day=E.dayKey();if(day===lastDay)return false;lastDay=day;reviewDay=day;week=E.weekKey(day);selections.clear();cancelActorFall();if(cuddleCleanup)cuddleCleanup();drag=null;
 const keepPhoto=dialogContext?.type==='photo';if(!keepPhoto)closeModal(false);render();scheduleMidnight();return true;
}
setInterval(rollover,15000);window.addEventListener('focus',()=>{rollover();scheduleMidnight();});window.addEventListener('pageshow',()=>{rollover();scheduleMidnight();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopFollowers();else{rollover();scheduleMidnight();startFollowers();}});
async function start(){try{S=await DB.load()||E.newState();E.validateState(S);if(E.migrate(S)){E.validateState(S);await DB.save(S,S.revision);}render();scheduleMidnight();prepareOffline();}catch(err){app.innerHTML=`<main class="page"><div class="empty-state"><h1>Your little world could not open.</h1><p>${h(err.message)} No saved records have been replaced.</p><p>Open the preview in a normal browser window. Avoid private browsing for saved progress.</p></div></main>`;console.error(err);}}
start();
})();
